// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbflJPxmcou81T-FZ_fUrrFxNFCazX8fw',
    appId: '1:223732614676:web:51fbab5723b9d1ec1f4901',
    messagingSenderId: '223732614676',
    projectId: 'fruits-app-7e74b',
    authDomain: 'fruits-app-7e74b.firebaseapp.com',
    storageBucket: 'fruits-app-7e74b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrWPubwpIVHiw3psbA2ZnQ7a_yydVMmbQ',
    appId: '1:223732614676:android:a8a1cfd7b2c4c9a31f4901',
    messagingSenderId: '223732614676',
    projectId: 'fruits-app-7e74b',
    storageBucket: 'fruits-app-7e74b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM9liKZnTT4JpO2pl06Iv0S-DdWsGOalg',
    appId: '1:223732614676:ios:00a543a5848f649a1f4901',
    messagingSenderId: '223732614676',
    projectId: 'fruits-app-7e74b',
    storageBucket: 'fruits-app-7e74b.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );
}
